import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Mai Tam | Full-stack Developer",
  description:
    "Portfolio of Mai Tam, a software engineering student and full-stack developer building web, mobile and AI-powered products.",
  keywords: [
    "Mai Tam",
    "maitamdev",
    "full-stack developer",
    "software engineering student",
    "Vietnam developer",
    "AI product builder",
    "Next.js",
    "TypeScript",
    "Flutter",
    "Supabase",
    "Solana",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Mai Tam",
    url: "https://github.com/maitamdev",
  },
  creator: "Mai Tam",
  alternates: {
    canonical: "https://maitamsite.site",
  },
  openGraph: {
    title: "Mai Tam | Full-stack Developer",
    description: "Web, mobile and AI-powered products built by Mai Tam.",
    url: "https://maitamsite.site",
    siteName: "Mai Tam Portfolio",
    type: "website",
  },
} as const;
